2024-01-04 00:41:00,523 - root - INFO - ----------------------------- Started new run @ 2024-01-04:0041 ----------------------------
2024-01-04 00:41:00,524 - root - INFO - -----------------------------  GETTING LINKS : data analyst ----------------------------
2024-01-04 00:41:00,525 - root - INFO - Searching for data-analyst
2024-01-04 00:41:00,895 - selenium.webdriver.common.selenium_manager - WARNING - The geckodriver version (0.33.0) detected in PATH at /usr/bin/geckodriver might not be compatible with the detected firefox version (121.0); currently, geckodriver 0.34.0 is recommended for firefox 121.*, so it is advised to delete the driver in PATH and retry
2024-01-04 00:44:56,573 - root - INFO - Getting page_source
2024-01-04 00:44:58,218 - root - INFO - Unique links: 226
2024-01-04 00:45:08,229 - root - INFO - -----------------------------  GETTING INFO : data analyst ----------------------------
2024-01-04 00:45:08,779 - root - INFO - Index 0 : 200
2024-01-04 00:45:09,414 - root - INFO - Index 1 : 200
2024-01-04 00:45:10,015 - root - INFO - Index 2 : 200
2024-01-04 00:45:10,668 - root - INFO - Index 3 : 200
2024-01-04 00:45:12,831 - root - INFO - Index 4 : 200
2024-01-04 00:45:13,391 - root - INFO - Index 5 : 200
2024-01-04 00:45:13,976 - root - INFO - Index 6 : 200
2024-01-04 00:45:14,600 - root - INFO - Index 7 : 200
2024-01-04 00:45:15,244 - root - INFO - Index 8 : 200
2024-01-04 00:45:15,851 - root - INFO - Index 9 : 200
2024-01-04 00:45:15,983 - root - INFO - Index 10 : 429
2024-01-04 00:45:15,983 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:45:21,586 - root - INFO - 	Success : 200
2024-01-04 00:45:22,150 - root - INFO - Index 11 : 200
2024-01-04 00:45:22,772 - root - INFO - Index 12 : 200
2024-01-04 00:45:23,348 - root - INFO - Index 13 : 200
2024-01-04 00:45:23,921 - root - INFO - Index 14 : 200
2024-01-04 00:45:24,611 - root - INFO - Index 15 : 200
2024-01-04 00:45:25,183 - root - INFO - Index 16 : 200
2024-01-04 00:45:25,797 - root - INFO - Index 17 : 200
2024-01-04 00:45:26,403 - root - INFO - Index 18 : 200
2024-01-04 00:45:27,012 - root - INFO - Index 19 : 200
2024-01-04 00:45:27,144 - root - INFO - Index 20 : 429
2024-01-04 00:45:27,145 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:45:32,211 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:45:37,830 - root - INFO - 	Success : 200
2024-01-04 00:45:38,398 - root - INFO - Index 21 : 200
2024-01-04 00:45:39,027 - root - INFO - Index 22 : 200
2024-01-04 00:45:39,630 - root - INFO - Index 23 : 200
2024-01-04 00:45:40,262 - root - INFO - Index 24 : 200
2024-01-04 00:45:40,886 - root - INFO - Index 25 : 200
2024-01-04 00:45:41,517 - root - INFO - Index 26 : 200
2024-01-04 00:45:42,153 - root - INFO - Index 27 : 200
2024-01-04 00:45:42,708 - root - INFO - Index 28 : 200
2024-01-04 00:45:43,397 - root - INFO - Index 29 : 200
2024-01-04 00:45:43,990 - root - INFO - Index 30 : 200
2024-01-04 00:45:44,116 - root - INFO - Index 31 : 429
2024-01-04 00:45:44,117 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:45:49,738 - root - INFO - 	Success : 200
2024-01-04 00:45:50,196 - root - INFO - Index 32 : 200
2024-01-04 00:45:50,788 - root - INFO - Index 33 : 200
2024-01-04 00:45:51,483 - root - INFO - Index 34 : 200
2024-01-04 00:45:52,065 - root - INFO - Index 35 : 200
2024-01-04 00:45:52,662 - root - INFO - Index 36 : 200
2024-01-04 00:45:53,244 - root - INFO - Index 37 : 200
2024-01-04 00:45:53,937 - root - INFO - Index 38 : 200
2024-01-04 00:45:54,480 - root - INFO - Index 39 : 200
2024-01-04 00:45:55,064 - root - INFO - Index 40 : 200
2024-01-04 00:45:55,204 - root - INFO - Index 41 : 429
2024-01-04 00:45:55,205 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:00,273 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:05,863 - root - INFO - 	Success : 200
2024-01-04 00:46:06,451 - root - INFO - Index 42 : 200
2024-01-04 00:46:07,055 - root - INFO - Index 43 : 200
2024-01-04 00:46:07,652 - root - INFO - Index 44 : 200
2024-01-04 00:46:08,302 - root - INFO - Index 45 : 200
2024-01-04 00:46:08,861 - root - INFO - Index 46 : 200
2024-01-04 00:46:09,575 - root - INFO - Index 47 : 200
2024-01-04 00:46:10,169 - root - INFO - Index 48 : 200
2024-01-04 00:46:10,778 - root - INFO - Index 49 : 200
2024-01-04 00:46:11,391 - root - INFO - Index 50 : 200
2024-01-04 00:46:11,549 - root - INFO - Index 51 : 429
2024-01-04 00:46:11,549 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:16,627 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:22,248 - root - INFO - 	Success : 200
2024-01-04 00:46:22,902 - root - INFO - Index 52 : 200
2024-01-04 00:46:23,499 - root - INFO - Index 53 : 200
2024-01-04 00:46:24,112 - root - INFO - Index 54 : 200
2024-01-04 00:46:24,657 - root - INFO - Index 55 : 200
2024-01-04 00:46:25,203 - root - INFO - Index 56 : 200
2024-01-04 00:46:25,767 - root - INFO - Index 57 : 200
2024-01-04 00:46:26,387 - root - INFO - Index 58 : 200
2024-01-04 00:46:27,003 - root - INFO - Index 59 : 200
2024-01-04 00:46:27,148 - root - INFO - Index 60 : 429
2024-01-04 00:46:27,149 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:32,224 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:37,763 - root - INFO - 	Success : 200
2024-01-04 00:46:38,322 - root - INFO - Index 61 : 200
2024-01-04 00:46:38,943 - root - INFO - Index 62 : 200
2024-01-04 00:46:39,578 - root - INFO - Index 63 : 200
2024-01-04 00:46:40,203 - root - INFO - Index 64 : 200
2024-01-04 00:46:40,914 - root - INFO - Index 65 : 200
2024-01-04 00:46:41,485 - root - INFO - Index 66 : 200
2024-01-04 00:46:42,007 - root - INFO - Index 67 : 200
2024-01-04 00:46:42,593 - root - INFO - Index 68 : 200
2024-01-04 00:46:42,726 - root - INFO - Index 69 : 429
2024-01-04 00:46:42,727 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:48,378 - root - INFO - 	Success : 200
2024-01-04 00:46:48,443 - root - INFO - Index 70 : 429
2024-01-04 00:46:48,443 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:46:54,057 - root - INFO - 	Success : 200
2024-01-04 00:46:54,617 - root - INFO - Index 71 : 200
2024-01-04 00:46:55,236 - root - INFO - Index 72 : 200
2024-01-04 00:46:55,889 - root - INFO - Index 73 : 200
2024-01-04 00:46:56,469 - root - INFO - Index 74 : 200
2024-01-04 00:46:57,044 - root - INFO - Index 75 : 200
2024-01-04 00:46:57,613 - root - INFO - Index 76 : 200
2024-01-04 00:46:58,240 - root - INFO - Index 77 : 200
2024-01-04 00:46:58,369 - root - INFO - Index 78 : 429
2024-01-04 00:46:58,369 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:04,065 - root - INFO - 	Success : 200
2024-01-04 00:47:04,135 - root - INFO - Index 79 : 429
2024-01-04 00:47:04,135 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:09,745 - root - INFO - 	Success : 200
2024-01-04 00:47:10,257 - root - INFO - Index 80 : 200
2024-01-04 00:47:10,837 - root - INFO - Index 81 : 200
2024-01-04 00:47:10,967 - root - INFO - Index 82 : 429
2024-01-04 00:47:10,967 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:18,815 - root - INFO - 	Success : 200
2024-01-04 00:47:19,333 - root - INFO - Index 83 : 200
2024-01-04 00:47:19,892 - root - INFO - Index 84 : 200
2024-01-04 00:47:20,520 - root - INFO - Index 85 : 200
2024-01-04 00:47:21,091 - root - INFO - Index 86 : 200
2024-01-04 00:47:21,641 - root - INFO - Index 87 : 200
2024-01-04 00:47:22,275 - root - INFO - Index 88 : 200
2024-01-04 00:47:22,875 - root - INFO - Index 89 : 200
2024-01-04 00:47:23,503 - root - INFO - Index 90 : 200
2024-01-04 00:47:24,037 - root - INFO - Index 91 : 200
2024-01-04 00:47:24,170 - root - INFO - Index 92 : 429
2024-01-04 00:47:24,171 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:29,785 - root - INFO - 	Success : 200
2024-01-04 00:47:30,259 - root - INFO - Index 93 : 200
2024-01-04 00:47:30,800 - root - INFO - Index 94 : 200
2024-01-04 00:47:31,566 - root - INFO - Index 95 : 200
2024-01-04 00:47:31,754 - root - INFO - Index 96 : 429
2024-01-04 00:47:31,755 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:37,394 - root - INFO - 	Success : 200
2024-01-04 00:47:37,941 - root - INFO - Index 97 : 200
2024-01-04 00:47:38,564 - root - INFO - Index 98 : 200
2024-01-04 00:47:39,145 - root - INFO - Index 99 : 200
2024-01-04 00:47:39,753 - root - INFO - Index 100 : 200
2024-01-04 00:47:39,886 - root - INFO - Index 101 : 429
2024-01-04 00:47:39,886 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:44,950 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:47:50,599 - root - INFO - 	Success : 200
2024-01-04 00:47:51,106 - root - INFO - Index 102 : 200
2024-01-04 00:47:51,833 - root - INFO - Index 103 : 200
2024-01-04 00:47:52,347 - root - INFO - Index 104 : 200
2024-01-04 00:47:52,959 - root - INFO - Index 105 : 200
2024-01-04 00:47:53,540 - root - INFO - Index 106 : 200
2024-01-04 00:47:54,187 - root - INFO - Index 107 : 200
2024-01-04 00:47:54,793 - root - INFO - Index 108 : 200
2024-01-04 00:47:55,422 - root - INFO - Index 109 : 200
2024-01-04 00:47:55,606 - root - INFO - Index 110 : 429
2024-01-04 00:47:55,606 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:00,683 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:06,301 - root - INFO - 	Success : 200
2024-01-04 00:48:06,781 - root - INFO - Index 111 : 200
2024-01-04 00:48:06,917 - root - INFO - Index 112 : 429
2024-01-04 00:48:06,917 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:12,536 - root - INFO - 	Success : 200
2024-01-04 00:48:13,013 - root - INFO - Index 113 : 200
2024-01-04 00:48:13,626 - root - INFO - Index 114 : 200
2024-01-04 00:48:14,374 - root - INFO - Index 115 : 200
2024-01-04 00:48:14,929 - root - INFO - Index 116 : 200
2024-01-04 00:48:15,510 - root - INFO - Index 117 : 200
2024-01-04 00:48:16,133 - root - INFO - Index 118 : 200
2024-01-04 00:48:16,276 - root - INFO - Index 119 : 429
2024-01-04 00:48:16,277 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:21,860 - root - INFO - 	Success : 200
2024-01-04 00:48:22,403 - root - INFO - Index 120 : 200
2024-01-04 00:48:22,540 - root - INFO - Index 121 : 429
2024-01-04 00:48:22,541 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:28,200 - root - INFO - 	Success : 200
2024-01-04 00:48:28,785 - root - INFO - Index 122 : 200
2024-01-04 00:48:29,460 - root - INFO - Index 123 : 200
2024-01-04 00:48:30,094 - root - INFO - Index 124 : 200
2024-01-04 00:48:30,717 - root - INFO - Index 125 : 200
2024-01-04 00:48:31,372 - root - INFO - Index 126 : 200
2024-01-04 00:48:31,946 - root - INFO - Index 127 : 200
2024-01-04 00:48:32,097 - root - INFO - Index 128 : 429
2024-01-04 00:48:32,098 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:37,685 - root - INFO - 	Success : 200
2024-01-04 00:48:38,353 - root - INFO - Index 129 : 200
2024-01-04 00:48:38,494 - root - INFO - Index 130 : 429
2024-01-04 00:48:38,495 - root - INFO - 	Ran into AuthWall, trying again in 5 secs...
2024-01-04 00:48:44,104 - root - INFO - 	Success : 200
2024-01-04 00:48:44,652 - root - INFO - Index 131 : 200
2024-01-04 00:48:45,223 - root - INFO - Index 132 : 200
2024-01-04 00:53:29,052 - root - ERROR - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/jobs_retriever_automailer/jobs_retriever_automailer/main.py", line 26, in <module>
    main[index] = get_job_info(link, index)
  File "/home/runner/work/jobs_retriever_automailer/jobs_retriever_automailer/modules/utils.py", line 222, in get_job_info
    response = requests.get(url, headers=headers)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
